feat: 🎸 add 5.4 chain events
PolymeshAssociation/polymesh-subquery pull request #143
Opened 2023-04-14 18:19 UTC by polymath-eric

### Description

⚠️ instances must include this update to process 5.4 blocks

### Breaking Changes

### JIRA Link

✅ Closes: [DA-639](https://polymesh.atlassian.net/browse/DA-639)

### Checklist

- [ ] Updated the Readme.md (if required) ?

2023-04-17 12:21 UTC, VictorVicente approved these changes

2023-04-17 12:59 UTC, prashantasdeveloper requested changes
It seems that there a lot of other events and txs added in 5.4. Refer - https://github.com/PolymeshAssociation/polymesh-sdk/pull/968

2023-04-18 07:04 UTC, prashantasdeveloper approved these changes

2023-04-18 07:04 UTC, merged

2023-04-18 07:14 UTC, polymath-eric commented
:tada: This PR is included in version 9.4.0-alpha.2 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-subquery/releases/tag/v9.4.0-alpha.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-04-28 15:40 UTC, polymath-eric commented
:tada: This PR is included in version 9.4.0 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-subquery/releases/tag/v9.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: