feat: 🎸 implement new ca events
PolymeshAssociation/polymesh-subquery pull request #203
Opened 2024-02-23 18:10 UTC by sansan

### Description

updates to use new event names for CA

### Breaking Changes

Requires resync 

### JIRA Link

https://polymesh.atlassian.net/browse/DA-1090

### Checklist

- [x] Updated the Readme.md (if required) ?

2024-02-26 13:23 UTC, polymath-eric approved these changes
lgtm

2024-02-26 16:26 UTC, prashantasdeveloper approved these changes

2024-02-26 16:41 UTC, prashantasdeveloper requested changes
ConfidentialAssets should by default set

2024-02-26 16:41 UTC, prashantasdeveloper commented on schema.graphql
> +  isFrozen: Boolean
```suggestion
  isFrozen: Boolean!
```
by default set this value to false while handling `AssetCreated` event

2024-02-26 17:17 UTC, prashantasdeveloper commented
@sansan I think you forgot to push changes and requested a re-review w/o updating the entity

2024-02-26 18:59 UTC, merged

2024-03-11 21:42 UTC, polymath-eric commented
:tada: This PR is included in version 13.0.0 :tada:

The release is available on [GitHub release](https://github.com/PolymeshAssociation/polymesh-subquery/releases/tag/v13.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: